from __future__ import annotations

import argparse
from pathlib import Path

import motmetrics as mm
import numpy as np
import pandas as pd


def evaluate_tracking(gt_file: str, pred_file: str, output_csv: str) -> dict[str, float]:
    gt_cols = ["frame", "id", "x", "y", "w", "h", "conf", "class", "visibility"]
    pred_cols = ["frame", "id", "x", "y", "w", "h", "conf", "x3d", "y3d", "z3d"]

    gt = pd.read_csv(gt_file, header=None, names=gt_cols)
    gt = gt[(gt["class"] == 1) & (gt["visibility"] > 0.25)].copy()

    pred = pd.read_csv(pred_file, header=None, names=pred_cols)

    acc = mm.MOTAccumulator(auto_id=True)

    for frame_id in sorted(gt["frame"].unique()):
        gt_frame = gt[gt["frame"] == frame_id]
        pred_frame = pred[pred["frame"] == frame_id]

        gt_ids = gt_frame["id"].tolist()
        pred_ids = pred_frame["id"].tolist()
        gt_boxes = gt_frame[["x", "y", "w", "h"]].values.tolist()
        pred_boxes = pred_frame[["x", "y", "w", "h"]].values.tolist()

        if len(gt_boxes) == 0 or len(pred_boxes) == 0:
            distances = np.empty((len(gt_ids), len(pred_ids)))
            distances[:] = np.nan
        else:
            distances = mm.distances.iou_matrix(gt_boxes, pred_boxes, max_iou=0.5)

        acc.update(gt_ids, pred_ids, distances)

    mh = mm.metrics.create()
    summary = mh.compute(
        acc,
        metrics=[
            "num_frames",
            "mota",
            "motp",
            "num_switches",
            "num_misses",
            "num_false_positives",
            "mostly_tracked",
            "mostly_lost",
        ],
        name="Tracking",
    )

    output_path = Path(output_csv)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(output_path)

    mota = float(summary["mota"].values[0])
    switches = float(summary["num_switches"].values[0])

    print("\n" + "=" * 60)
    print("TRACKING RESULTS")
    print("=" * 60)
    print(
        mm.io.render_summary(
            summary,
            formatters=mh.formatters,
            namemap=mm.io.motchallenge_metric_names,
        )
    )
    print("=" * 60)
    print(f"MOTA = {mota:.1%}")
    print(f"ID switches = {int(switches)}")
    print(f"Metrics CSV written to: {output_path}")

    return {
        "mota": mota,
        "id_switches": switches,
        "metrics_csv": str(output_path),
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="P4 tracking evaluation (MOT metrics)")
    parser.add_argument(
        "--gt-file",
        default="data/raw/MOT17/train/MOT17-02-FRCNN/gt/gt.txt",
        help="Ground-truth MOT file",
    )
    parser.add_argument(
        "--pred-file",
        default="results/p4/MOT17-02.txt",
        help="Predicted MOT file generated by tracking",
    )
    parser.add_argument(
        "--output-csv",
        default="results/p4/metrics_bytetrack.csv",
        help="Output CSV for MOT metrics",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    evaluate_tracking(gt_file=args.gt_file, pred_file=args.pred_file, output_csv=args.output_csv)


if __name__ == "__main__":
    main()
