from __future__ import annotations

import argparse
import json
from pathlib import Path

import motmetrics as mm
import numpy as np
import pandas as pd

if not hasattr(np, "asfarray"):
    # motmetrics relies on np.asfarray, removed in NumPy >= 2.0.
    np.asfarray = lambda arr: np.asarray(arr, dtype=float)


def evaluate_tracking(gt_file: str, pred_file: str, output_csv: str) -> dict[str, float]:
    gt_cols = ["frame", "id", "x", "y", "w", "h", "conf", "class", "visibility"]
    pred_cols = ["frame", "id", "x", "y", "w", "h", "conf", "x3d", "y3d", "z3d"]

    gt = pd.read_csv(gt_file, header=None, names=gt_cols)
    gt = gt[(gt["class"] == 1) & (gt["visibility"] > 0.25)].copy()

    pred = pd.read_csv(pred_file, header=None, names=pred_cols)

    acc = mm.MOTAccumulator(auto_id=True)

    for frame_id in sorted(gt["frame"].unique()):
        gt_frame = gt[gt["frame"] == frame_id]
        pred_frame = pred[pred["frame"] == frame_id]

        gt_ids = gt_frame["id"].tolist()
        pred_ids = pred_frame["id"].tolist()
        gt_boxes = gt_frame[["x", "y", "w", "h"]].values.tolist()
        pred_boxes = pred_frame[["x", "y", "w", "h"]].values.tolist()

        if len(gt_boxes) == 0 or len(pred_boxes) == 0:
            distances = np.empty((len(gt_ids), len(pred_ids)))
            distances[:] = np.nan
        else:
            distances = mm.distances.iou_matrix(gt_boxes, pred_boxes, max_iou=0.5)

        acc.update(gt_ids, pred_ids, distances)

    mh = mm.metrics.create()
    summary = mh.compute(
        acc,
        metrics=[
            "num_frames",
            "mota",
            "motp",
            "num_switches",
            "idf1",
            "num_misses",
            "num_false_positives",
            "mostly_tracked",
            "mostly_lost",
        ],
        name="Tracking",
    )

    output_path = Path(output_csv)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(output_path)

    mota = float(summary["mota"].values[0])
    motp = float(summary["motp"].values[0])
    switches = float(summary["num_switches"].values[0])
    idf1 = float(summary["idf1"].values[0])

    # HOTA is not provided by motmetrics. We expose an explicit fallback when trackeval is unavailable.
    hota: float | None = None
    hota_source = "unavailable"
    try:
        import trackeval  # type: ignore  # noqa: F401

        hota_source = "trackeval-installed-not-integrated"
    except Exception:
        hota_source = "trackeval-not-installed"

    print("\n" + "=" * 60)
    print("TRACKING RESULTS")
    print("=" * 60)
    print(
        mm.io.render_summary(
            summary,
            formatters=mh.formatters,
            namemap=mm.io.motchallenge_metric_names,
        )
    )
    print("=" * 60)
    print(f"MOTA = {mota:.1%}")
    print(f"MOTP = {motp:.4f}")
    print(f"IDF1 = {idf1:.1%}")
    print(f"ID switches = {int(switches)}")
    print(f"HOTA = {'N/A' if hota is None else f'{hota:.1%}'} ({hota_source})")
    print(f"Metrics CSV written to: {output_path}")

    return {
        "mota": mota,
        "motp": motp,
        "id_switches": switches,
        "idf1": idf1,
        "hota": hota,
        "hota_source": hota_source,
        "metrics_csv": str(output_path),
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="P4 tracking evaluation (MOT metrics)")
    parser.add_argument(
        "--gt-file",
        default="data/raw/MOT17/train/MOT17-02-FRCNN/gt/gt.txt",
        help="Ground-truth MOT file",
    )
    parser.add_argument(
        "--pred-file",
        default="results/p4/MOT17-02.txt",
        help="Predicted MOT file generated by tracking",
    )
    parser.add_argument(
        "--output-csv",
        default="results/p4/metrics_bytetrack.csv",
        help="Output CSV for MOT metrics",
    )
    parser.add_argument(
        "--output-json",
        default="results/p4/metrics_bytetrack.json",
        help="Output JSON report with MOTA/MOTP/ID switches/IDF1/HOTA fallback details",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    results = evaluate_tracking(gt_file=args.gt_file, pred_file=args.pred_file, output_csv=args.output_csv)

    output_json_path = Path(args.output_json)
    output_json_path.parent.mkdir(parents=True, exist_ok=True)
    output_json_path.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(f"Metrics JSON written to: {output_json_path}")


if __name__ == "__main__":
    main()
